{% set name = "napari-hough-circle-detector" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-hough-circle-detector-{{ version }}.tar.gz
  sha256: b6159b7fc5048264490f55cce11230d4a920709685adc4e6ae25bf44e4ef3b5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - numpy
    - python >=3.8
    - opencv
    - qtpy
    - scikit-image

test:
  imports:
    - napari_hough_circle_detector
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-hough-circle-detector/
  summary: An interactive Hough transform for napari.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
