{% set name = "napari-hough-circle-detector" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-hough-circle-detector-{{ version }}.tar.gz
  sha256: f17ed5b57cd9e2a0007ef90b6eee8b3ef69b7e26dd6494445a4e15ad5d12e848

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - napari
    - numpy
    - python >=3.8,<3.11
    - opencv
    - qtpy

test:
  imports:
    - napari_hough_circle_detector
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-hough-circle-detector/
  summary: An interactive Hough transform for napari.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
